### ISSUE TITLE
how to use "[FONTNAME] [OTHER PARAMETERS]" ?

### ISSUE THREAD

**Issue by juhp** [sudipshil9862/whichfont#1]
```shellsession
$ whichfont --help
Usage: whichfont [OPTIONS] <INPUT> [OTHER PARAMETERS]
:
```

Can you please add some documentation/examples how to use `[OTHER PARAMETERS]`?

*edit*: above updated to drop [FONTNAME]

**Comment by juhp** [comment]
https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcnameparse.html may help

**Comment by juhp** [comment]
Can you add `whichfont U+0985 family style familylang lang` as an example to the readme?

**Comment by sudipshil9862** [comment]
feature added
