### ISSUE TITLE
add option to print utf8 hex sequence

### ISSUE THREAD

**Issue by juhp** [sudipshil9862/whichfont#2]
```shellsession
$ whichfont '　'
Character: 　
NuosuSIL-Regular.ttf: "Nuosu SIL" "Regular"
```

It would be useful here to know the utf8 hex sequence for the character

**Comment by juhp** [comment]
Searching it seems in this case the character is U+3000 (Ideographic Space)

**Comment by juhp** [comment]
Maybe option `-u`

**Comment by sudipshil9862** [comment]
adding -u to print unicode

**Comment by sudipshil9862** [comment]
feature added

**Comment by sudipshil9862** [comment]
example:1

$ ./run.sh অA
input_char: অA

Character: অ
Lohit-Bengali.ttf: "Lohit Bengali" "Regular"

Character: A
NotoSans[wght].ttf: "Noto Sans" "Regular"


------------------------------------------------
example:2

$ ./run.sh -u অA
ninja: no work to do.
input_char: অA

Character: অ
unicode: U+0041
Lohit-Bengali.ttf: "Lohit Bengali" "Regular"

Character: A
unicode: U+0041
NotoSans[wght].ttf: "Noto Sans" "Regular"

**Comment by juhp** [comment]
```
$ whichfont অA
:
Character: অ
unicode: U+0041
:
```
clearly incorrect, though it works for single character

**Comment by juhp** [comment]
Also I think it would be okay to write the character and codepoint on the same line.

**Comment by sudipshil9862** [comment]
understood the problem

**Comment by sudipshil9862** [comment]
it was a problem of printing wrong unicode.
